language: cpp
branches:
  only:
    - master
    - develop
os:
  - linux
  - osx
dist: trusty         # cmake 3.2
osx_image: xcode7.3  # OSX 10.11, cmake 3.5
env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug
cache:
  - ccache
  - directories: build/llvm


before_install:
  - cmake --version

script:
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - cmake --build .
